// Simulate topic data from server until backend is setup
import { CandyconDpad } from './candycon-dpad.model';

var baseUrl = 'https://www.gamestop.com/gaming-accessories/thumb-grips/nintendo-switch/products/candy-con-d-pad---';
export const DPADS: CandyconDpad[] = [
  {
    id: 1,
    UPC: 840305903930,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-DPad-Arctic White',
    name: 'CANDY CON DPad',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style.The THUMB STICKS come ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/dpad_arcticwhite.png','https://media.gamestop.com/i/gamestop/20009956-b9072aa8_ALT02?$pdp2x$'],
    productUrl: baseUrl + 'arctic-white/402235.html',
    partColor: 'Arctic White',
    price: 3.99,
    productLength: 3.35,
    productWidth: 0.39,
    productHeight: 4.13,
    productWeight: 	0.02
  },
  {
    id: 2,
    UPC: 840305903947,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-DPad-BoltYellow',
    name: 'CANDY CON DPad',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style.The THUMB STICKS come ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/dpad_boltyellow.png', 'https://media.gamestop.com/i/gamestop/20009956-6f07b498_ALT02?$pdp2x$'],
    productUrl: baseUrl + 'bolt-yellow/402236.html',
    partColor: 'Bolt Yellow',
    price: 3.99,
    productLength: 3.35,
    productWidth: 0.39,
    productHeight: 4.13,
    productWeight: 	0.02
  },
  {
    id: 3,
    UPC: 840305903893,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-DPad- ChilliRed',
    name: 'CANDY CON DPad',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style.The THUMB STICKS come ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/dpad_chillired.png', 'https://media.gamestop.com/i/gamestop/20009956-d206c689_ALT02?$pdp2x$'],
    productUrl: baseUrl + 'chilli-red/402231.html',
    partColor: 'Chilli Red',
    price: 3.99,
    productLength: 3.35,
    productWidth: 0.39,
    productHeight: 4.13,
    productWeight: 	0.02
  },
  {
    id: 4,
    UPC: 840305904715,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-DPad-CyanBlast',
    name: 'CANDY CON DPad',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style.The THUMB STICKS come ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/dpad_cyanblast.png', 'https://media.gamestop.com/i/gamestop/20009956-e306b288_ALT02?$pdp2x$'],
    productUrl: baseUrl + 'cyan-blast/402265.html',
    partColor: 'Cyan Blast',
    price: 3.99,
    productLength: 3.35,
    productWidth: 0.39,
    productHeight: 4.13,
    productWeight: 	0.02
  },
  {
    id: 5,
    UPC: 840305904692,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-DPad-LemonBurst',
    name: 'CANDY CON DPad',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style.The THUMB STICKS come ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/dpad_lemonburst.png', 'https://media.gamestop.com/i/gamestop/20009956-6d073699_ALT02?$pdp2x$'],
    productUrl: baseUrl + 'lemon-burst/402263.html',
    partColor: 'Lemon Burst',
    price: 3.99,
    productLength: 3.35,
    productWidth: 0.39,
    productHeight: 4.13,
    productWeight: 	0.02
  },
  {
    id: 6,
    UPC: 840305904708,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-DPad-MidnightPurple',
    name: 'CANDY CON DPad',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style.The THUMB STICKS come ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/dpad_midnightpurple.png', 'https://media.gamestop.com/i/gamestop/20009956-0e09d2dd_ALT02?$pdp2x$'],
    productUrl: baseUrl + 'midnight-purple/402264.html',
    partColor: 'Midnight Purple',
    price: 3.99,
    productLength: 3.35,
    productWidth: 0.39,
    productHeight: 4.13,
    productWeight: 	0.02
  },
  {
    id: 7,
    UPC: 840305903916,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-DPad- OceanMirage',
    name: 'CANDY CON DPad',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style.The THUMB STICKS come ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/dpad_oceanmirage.png', 'https://media.gamestop.com/i/gamestop/20009956-ed06aa8a_ALT02?$pdp2x$'],
    productUrl: baseUrl + 'ocean-mirage/402237.html',
    partColor: 'Ocean Mirage',
    price: 3.99,
    productLength: 3.35,
    productWidth: 0.39,
    productHeight: 4.13,
    productWeight: 	0.02
  },
  {
    id: 8,
    UPC: 	840305903916,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-DPad-OnyxBlack',
    name: 'CANDY CON DPad',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style.The THUMB STICKS come ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/dpad_onyxblack.png', 'https://media.gamestop.com/i/gamestop/20009956-ed06aa8a_ALT02?$pdp2x$'],
    productUrl: baseUrl + 'onyx-black/402233.html',
    partColor: 'Onyx Black',
    price: 3.99,
    productLength: 3.35,
    productWidth: 0.39,
    productHeight: 4.13,
    productWeight: 	0.02
  },
  {
    id: 9,
    UPC: 	840305903923,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-DPad-OrangeCrush',
    name: 'CANDY CON DPad',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style.The THUMB STICKS come ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/dpad_orangecrush.png', 'https://media.gamestop.com/i/gamestop/20009956-c307c8a8_ALT02?$pdp2x$'],
    productUrl: baseUrl + 'orange-crush/402234.html',
    partColor: 'Orange Crush',
    price: 3.99,
    productLength: 3.35,
    productWidth: 0.39,
    productHeight: 4.13,
    productWeight: 	0.02
  },
  {
    id: 10,
    UPC: 	840305903909,
    brandName: 'CANDY CON',
    vendorPartNumber: '	24VG-GSPL-CC-DPad-PrincessPink',
    name: 'CANDY CON DPad',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style.The THUMB STICKS come ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/dpad_princesspink.png', 'https://media.gamestop.com/i/gamestop/20009956-3b08e6bb_ALT02?$pdp2x$'],
    productUrl: baseUrl + 'princess-pink/402232.html',
    partColor: 'Princess Pink',
    price: 3.99,
    productLength: 3.35,
    productWidth: 0.39,
    productHeight: 4.13,
    productWeight: 	0.02
  },
  {
    id: 11,
    UPC: 840305904722,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-DPad-TiaraTeal',
    name: 'CANDY CON DPad',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style.The THUMB STICKS come ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/dpad_tiarateal.png', 'https://media.gamestop.com/i/gamestop/20009285-d906c289?$pdp2x$'],
    productUrl: baseUrl + 'tiara-teal/402261.html',
    partColor: 'Tiara Teal',
    price: 3.99,
    productLength: 3.35,
    productWidth: 0.39,
    productHeight: 4.13,
    productWeight: 	0.02
  },
  {
    id: 12,
    UPC: 840305904685,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-DPad-ToxicWaste',
    name: 'CANDY CON DPad',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style.The THUMB STICKS come ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/dpad_toxicwaste.png', 'https://media.gamestop.com/i/gamestop/20009956-6d07989a_ALT02?$pdp2x$'],
    productUrl: baseUrl + 'toxic-waste/402262.html',
    partColor: 'Toxic Waste',
    price: 3.99,
    productLength: 3.35,
    productWidth: 0.39,
    productHeight: 4.13,
    productWeight: 	0.02
  },
];
