// Simulate topic data from server until backend is setup
import { CandyconFaceplate } from './candycon-faceplate.model';

var baseUrl = 'https://www.gamestop.com/gaming-accessories/skins/nintendo-switch/products/candy-con-face-plate--';
export const FACEPLATES: CandyconFaceplate[] = [
  
  {
    id: -1,
    UPC: 840305903848,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-Combo-ArcticWhite',
    name: 'CANDY CON Faceplate',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style. The FACE PLATE comes ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['assets/products/faceplate_arcticwhite.png'],
    productUrl: 'https://www.gamestop.com/gaming-accessories/controllers/nintendo-switch/products/candy-con-combo-pack-controller-kit---arctic-white/402225.html',
    partColor: 'Arctic White',
    price: 14.99,
    productLength: 6.89,
    productWidth: 1.38,
    productHeight: 5.31,
    productWeight: 0.33
  },
  {
    id: -2,
    UPC: 840305904609,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-Combo-OnyxBlack',
    name: 'CANDY CON Faceplate',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style. The FACE PLATE comes ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['assets/products/faceplate_onyxblack.png'],
    productUrl: 'https://www.gamestop.com/gaming-accessories/controllers/nintendo-switch/products/candy-con-combo-pack-controller-kit---onyx-black/402254.html',
    partColor: 'Onyx Black',
    price: 14.99,
    productLength: 6.89,
    productWidth: 1.38,
    productHeight: 5.31,
    productWeight: 0.33
  },
  {
    id: 1,
    UPC: 840305904548,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-FacePlate-BoltYellow',
    name: 'CANDY CON Faceplate',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style. The FACE PLATE comes ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/faceplate_boltyellow.png','https://media.gamestop.com/i/gamestop/20009280-6f07b498_ALT03?$pdp2x$'],
    productUrl: baseUrl + 'bolt-yellow/402230.html',
    partColor: 'Bolt Yellow',
    price: 9.99,
    productLength: 5.31,
    productWidth: 1.38,
    productHeight: 6.89,
    productWeight: 	0.18
  },
  {
    id: 2,
    UPC: 840305903855,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-FacePlate-ChilliRed',
    name: 'CANDY CON Faceplate',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style. The FACE PLATE comes ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/faceplate_chillired.png','https://media.gamestop.com/i/gamestop/20009280_ALT01?$pdp2x$'],
    productUrl: baseUrl + '-chilli-red/402226.html',
    partColor: 'Chilli Red',
    price: 9.99,
    productLength: 5.31,
    productWidth: 1.38,
    productHeight: 6.89,
    productWeight: 	0.18
  },
  {
    id: 3,
    UPC: 840305904647,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-FacePlate-CyanBlast',
    name: 'CANDY CON Faceplate',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style. The FACE PLATE comes ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/faceplate_cyanblast.png', 'https://media.gamestop.com/i/gamestop/20009280-e306b288_ALT03?$pdp2x$'],
    productUrl: baseUrl + '-cyan-blast/402258.html',
    partColor: 'Cyan Blast',
    price: 9.99,
    productLength: 5.31,
    productWidth: 1.38,
    productHeight: 6.89,
    productWeight: 	0.18
  },
  {
    id: 4,
    UPC: 840305903886,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-FacePlate-ElectroCity',
    name: 'CANDY CON Faceplate',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style. The FACE PLATE comes ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/faceplate_electrocity.png', 'https://media.gamestop.com/i/gamestop/20009280-c9072ca9_ALT03?$pdp2x$'],
    productUrl: baseUrl + '-electro-city/402229.html',
    partColor: 'Electro City',
    price: 9.99,
    productLength: 5.31,
    productWidth: 1.38,
    productHeight: 6.89,
    productWeight: 	0.18
  },
  {
    id: 5,
    UPC: 840305904661,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-FacePlate-Midnight Purple',
    name: 'CANDY CON Faceplate',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style. The FACE PLATE comes ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/faceplate_midnightpurple.png', 'https://media.gamestop.com/i/gamestop/20009280-0e09d2dd_ALT02?$pdp2x$'],
    productUrl: baseUrl + '-midnight-purple/402260.html',
    partColor: 'Midnight Purple',
    price: 9.99,
    productLength: 5.31,
    productWidth: 1.38,
    productHeight: 6.89,
    productWeight: 	0.18
  },
  {
    id: 6,
    UPC: 840305904630,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-FacePlate-OrangeCrush',
    name: 'CANDY CON Faceplate',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style. The FACE PLATE comes ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/faceplate_orangecrush.png', 'https://media.gamestop.com/i/gamestop/20009280-c307c8a8_ALT03?$pdp2x$'],
    productUrl: baseUrl + '-orange-crush/402257.html',
    partColor: 'Orange Crush',
    price: 9.99,
    productLength: 5.31,
    productWidth: 1.38,
    productHeight: 6.89,
    productWeight: 	0.18
  },
  {
    id: 7,
    UPC: 840305903862,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-FacePlate-PrincessPink',
    name: 'CANDY CON Faceplate',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style. The FACE PLATE comes ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/faceplate_princesspink.png', 'https://media.gamestop.com/i/gamestop/20009280-3b08e6bb_ALT03?$pdp2x$'],
    productUrl: baseUrl + '-princess-pink/402227.html',
    partColor: 'Princess Pink',
    price: 9.99,
    productLength: 5.31,
    productWidth: 1.38,
    productHeight: 6.89,
    productWeight: 	0.18
  },
  {
    id: 8,
    UPC: 840305903879,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-FacePlate-RetroShapes',
    name: 'CANDY CON Faceplate',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style. The FACE PLATE comes ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/faceplate_retroshapes.png', 'https://media.gamestop.com/i/gamestop/20009280-d2079ca9_ALT03?$pdp2x$'],
    productUrl: baseUrl + '-retro-shapes/402228.html',
    partColor: 'Retro Shapes',
    price: 9.99,
    productLength: 5.31,
    productWidth: 1.38,
    productHeight: 6.89,
    productWeight: 	0.18
  },
  {
    id: 9,
    UPC: 	840305904616,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-FacePlate-TiaraTeal',
    name: 'CANDY CON Faceplate',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style. The FACE PLATE comes ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/faceplate_tiarateal.png', 'https://media.gamestop.com/i/gamestop/20009280-d906c289_ALT03?$pdp2x$'],
    productUrl: baseUrl + '-tiara-teal/402255.html',
    partColor: 'Tiara Teal',
    price: 9.99,
    productLength: 5.31,
    productWidth: 1.38,
    productHeight: 6.89,
    productWeight: 	0.18
  },
  {
    id: 10,
    UPC: 	840305904623,
    brandName: 'CANDY CON',
    vendorPartNumber: '24VG-GSPL-CC-FacePlate-ToxicWaste',
    name: 'CANDY CON Faceplate',
    description: 'Welcome to CANDY CON, the newest line in customizable controllers. Grab your BASE Customizable Controller, Pick D-Pads, Thumb Sticks, and a Face Plate and create your own unique Controller. Craft your CANDY CON masterpiece and show off your incredible combos in style. The FACE PLATE comes ready to add to your new CANDY CON Controller, over 10 colors to choose from to easily mix and match. CREATE. PLAY. REPEAT Mix with CANDY CON BASE UNIT, sold separately',
    imageUrls: ['https://cclab.blob.core.windows.net/part-images/faceplate_toxicwaste.png', 'https://media.gamestop.com/i/gamestop/20009280-6d07989a_ALT03?$pdp2x$'],
    productUrl: baseUrl + '-toxic-waste/402256.html',
    partColor: 'Toxic Waste',
    price: 9.99,
    productLength: 5.31,
    productWidth: 1.38,
    productHeight: 6.89,
    productWeight: 	0.18
  },
];
